version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    mem_limit: 2G  
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: guided_project_php_myadmin
    restart: unless-stopped
    mem_limit: 1G  

    environment:
      - PMA_HOST=mysql
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
